### ISSUE TITLE
Support newer version of impala

### ISSUE THREAD

**Issue by ghost** [piersharding/dplyrimpaladb#7]
The code in this repository is for an older version of Impala which is more similar to the Hive thrift interface.  I've forked this and updated it to use newer versions of Impala at https://github.com/WheresAlice/dplyrimpaladb

It works on my machine, but I'm no R expert so I've not created a pull request yet. Specifically I'm concerned that the new jar file names are hardcoded, so this would need updating whenever they change.  I've also only run this on a Fedora workstation so far.

**Comment by piersharding** [comment]
Hi - thank for testing this out.  Can you let me know what version of ImpalaDB you are using and I'll figure something out.  I was never happy with hard-coding the jars - I should add an options() parameter for overriding them.

Cheers,
Piers Harding.

**Comment by ghost** [comment]
`SELECT VERSION();` gives

impalad version 2.3.0-cdh5.5.1 RELEASE (build 7520c3adc48a17d78e79df0f91c9b85a2d658957)
Built on Tue, 12 Jan 2016 11:11:12 PST

we're using SSL and authentication, and passing all of those options in through the options works just fine.  One thing of note though, it needs the options uid and pwd for the username and password in addition to the username and password parameter.

``` R
reference <- src_impaladb('reference', host='impala.example.org', user='my_username', password='my_password', opts=list(auth="noSasl",AuthMech="4",SSLTrustStorePwd="changeit",SSLKeyStorePwd="changeit",SSLKeyStore="/etc/impala.jks",SSLTrustStore="/etc/impala.jks",uid="my_username",pwd="my_password") )
all_dates <- tbl(calendar, sql('SELECT * FROM calendar LIMIT 10'))
head(all_dates)
```

**Comment by piersharding** [comment]
Hi - could you please test the latest version that I have pushed up.  I have added an option dplyr.jdbc.jarfiles which should prepend jar files of your choice to the search path.   so something like:

```
options(dplyr.jdbc.jarfiles=c("hive_metastore.jar",
                            "hive_service.jar",
                            "ImpalaJDBC41.jar",
                            "libfb303-0.9.0.jar",
                            "libthrift-0.9.0.jar",
                            "log4j-1.2.14.jar",
                            "ql.jar",
                            "slf4j-api-1.5.11.jar",
                            "slf4j-log4j12-1.5.11.jar",
                            "TCLIServiceClient.jar",
                            "zookeeper-3.4.6.jar"
                            ))
reference <- src_impaladb('reference', host='impala.example.org', user='my_username', password='my_password', opts=list(auth="noSasl",AuthMech="4",SSLTrustStorePwd="changeit",SSLKeyStorePwd="changeit",SSLKeyStore="/etc/impala.jks",SSLTrustStore="/etc/impala.jks",uid="my_username",pwd="my_password") )
all_dates <- tbl(calendar, sql('SELECT * FROM calendar LIMIT 10'))
head(all_dates)
```

Thanks,
Piers.

**Comment by ghost** [comment]
Sure, I'll give it a test when I'm back in the office on Monday.

**Comment by ghost** [comment]
You need to update the driverclass.  The old one is 'org.apache.hive.jdbc.HiveDriver' and the new one is 'com.cloudera.impala.jdbc41.Driver'.  This assumes you're not using an old version of Java, in which case you'd require an older class from a separate download.

**Comment by piersharding** [comment]
OK - I've added additional parameters to src_impaladb() for classpath, scheme, driverclass, and jarfiles so you should now be able to override it all with something like:

```
reference <- src_impaladb('reference',
                          host='impala.example.org', 
                          user='my_username',
                          password='my_password', 
                          driverclass="com.cloudera.impala.jdbc41.Driver",
                          scheme="impala",
                          jarfiles=c("hive_metastore.jar",
                                      "hive_service.jar",
                                      "ImpalaJDBC41.jar",
                                      "libfb303-0.9.0.jar",
                                      "libthrift-0.9.0.jar",
                                      "log4j-1.2.14.jar",
                                      "ql.jar",
                                      "slf4j-api-1.5.11.jar",
                                      "slf4j-log4j12-1.5.11.jar",
                                      "TCLIServiceClient.jar",
                                      "zookeeper-3.4.6.jar"
                                      ),
                          opts=list(auth="noSasl",
                                    AuthMech="4",
                                    SSLTrustStorePwd="changeit",
                                    SSLKeyStorePwd="changeit",
                                    SSLKeyStore="/etc/impala.jks",
                                    SSLTrustStore="/etc/impala.jks",
                                    uid="my_username",
                                    pwd="my_password") )
all_dates <- tbl(calendar, sql('SELECT * FROM calendar LIMIT 10'))
head(all_dates)
```

Hopefully this will do it.

Cheers,
Piers Harding.

**Comment by ghost** [comment]
Still getting an error for driverClass

> reference <- src_impaladb('reference', host='impala.a.maximus.skybet.net', user='my_username', password='my_password', driverclass="com.cloudera.impala.jdbc41.Driver", scheme="impala", opts=list(auth="noSasl",AuthMech="4",SSLTrustStorePwd="changeit",SSLKeyStorePwd="changeit",SSLKeyStore="/etc/impala.jks",SSLTrustStore="/etc/impala.jks",uid="my_username",pwd="my_password") )

Error in dbConnect(JDBC(driverclass, expandAndCheckClassPath(classpath = classpath,  : 
  error in evaluating the argument 'drv' in selecting a method for function 'dbConnect': Error in .jfindClass(as.character(driverClass)[1]) : class not found

**Comment by ghost** [comment]
Wait, my mistake - the remove and reinstall hadn't actually worked.  That does appear to be working for me now.

**Comment by piersharding** [comment]
OK , great - if this is a workable solution for you, then I'll close the issue.

Cheers,
Piers Harding.

**Comment by ghost** [comment]
Yep, happy for this to be closed. Do you want me to submit a pull request for the readme to reflect these changes and my testing/installation process?

**Comment by piersharding** [comment]
That would be great - thanks.

**Comment by ghost** [comment]
Code and documentation now supports the latest version of impala, happy to close this issue.

**Comment by ravidas1989** [comment]
Hi...when i used src_impaladb , i got the same error
Error in dbConnect(JDBC(driverclass, expandAndCheckClassPath(classpath = classpath, : 
error in evaluating the argument 'drv' in selecting a method for function 'dbConnect': Error in .jfindClass(as.character(driverClass)[1]) : class not found

I read through and it meant "remove and reinstall" has worked.. can i know what is the exact solution for this error.Please let me know since i am facing the same issue when i get to connect to impalausing dplyrimpaladb package

**Comment by ghost** [comment]
That typically means that the impala driver java jars aren't being found. Do you have the jars in your classpath or are you passing in a specific classpath in R?

**Comment by ghost** [comment]
Also, it's probably best to split this into a separate issue.

**Comment by ravidas1989** [comment]
Hi,
thanks for the response. i have the jar files in my local drive. and i am using that local drive link and using it in the classpath argument. What should the class path contain???

**Comment by piersharding** [comment]
Hi -

Follow the example in the usage section here https://github.com/piersharding/dplyrimpaladb .  The classpath parameter for src_impaladb() should be set to the directory that the ImpalaDB jar files are in, and you must list all the necessary jars in the jarfiles parameter.  If you are still having trouble then please supply a code example of what you are trying to do.

As WheresAlice stated - it would be better to open a new issue  as this issue is not the appropriate place for your problem.

Cheers,
Piers Harding.

**Comment by ghost** [comment]
My colleague had a similar issue with this on his Macbook today, which appears to have a specific issue around Java.

Running `R CMD javareconf` resolved this for me on my Mac, but he's still struggling to get this command to run. It might be worth trying running this.

**Comment by ravidas1989** [comment]
Hi WheresAlice,

Executing the code i am also getting the error

"Error in dbConnect(JDBC(driverclass, expandAndCheckClassPath(driverclass = driverclass),  : 
  error in evaluating the argument 'drv' in selecting a method for function 'dbConnect': Error in path.expand(unlist(strsplit(classPath, .Platform$path.sep))) : 
  invalid 'path' argument  "

1.I have given the classpath = path where i have downloaded impala JDBC jar files and also given in the "path " variable while configuring environmental variable settings.
2. i have also Installed RJDBC ,dplyr and required packages and also dplyrimpaladb package.

But still i face this issue. I have referred to the github link
https://github.com/piersharding/dplyrimpaladb 

and worked accordingly. But stuck completely because of this error. could you please let me know how to solve this issue.it is really taking my complete day.!!!

Attached the screenshot of code and the error.

![dbconnect_error](https://cloud.githubusercontent.com/assets/17778448/13779705/642c3a8a-eae2-11e5-8375-625e7918790d.PNG)

"

**Comment by piersharding** [comment]
The following is a working example for my local install of ImpalaDB:

```
lahman <- src_impaladb('lahman',
                          host='dragon.local.net',
                          driverclass="com.cloudera.impala.jdbc41.Driver",
                          classpath="/opt/lib",
                          scheme="impala",
                          jarfiles=c('hive_metastore.jar', 'ImpalaJDBC41.jar', 'libthrift-0.9.0.jar', 'ql.jar', 'slf4j-log4j12-1.5.11.jar', 'zookeeper-3.4.6.jar', 'hive_service.jar', 'libfb303-0.9.0.jar', 'log4j-1.2.14.jar', 'slf4j-api-1.5.11.jar', 'TCLIServiceClient.jar'),
                          opts=list(AuthMech="0"))
```

I'm guessing that  classpath for you should be  C:/ravi/my_backup/Big_Data_and_Hadoop/Nielson/NDX/Impala/impala-jdbc-0.5-2  and you need to make sure that the above jar files are in that directory.

Outside of that you may need to adjust the opts list to reflect your authentication scheme.
